stages:
  - test
  - build
  - security

include:
  - project: 'meganerd/ci-templates'
    file: '/go/test.yml'
    ref: 'v1.0.2'
  - project: 'meganerd/ci-templates'
    file: '/go/lint.yml'
    ref: 'v1.0.2'
  - project: 'meganerd/ci-templates'
    file: '/go/build.yml'
    ref: 'v1.0.2'
  - project: 'meganerd/ci-templates'
    file: '/go/security.yml'
    ref: 'v1.0.2'

variables:
  GO_IMAGE: "golang:1.26"
  GOLANGCI_LINT_IMAGE: "golangci/golangci-lint:v2.11"
  GO_BUILD_PATH: "./cmd/pai-opencode/"
  GO_BINARY_NAME: "pai-opencode"
